# Generated by Django 5.1.1 on 2024-11-30 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='event_date',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='event_name',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='is_accepted',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='qr_code',
        ),
        migrations.AddField(
            model_name='ticket',
            name='event_details',
            field=models.TextField(default='Event details not available'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='seat_number',
            field=models.IntegerField(),
        ),
    ]
